on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: actions/setup-build-action@v2
        with:
          python-version: 3.11

      - name: Build Docker Image
        run: docker build -t myapp
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Docker Image
        run: docker run --run -d -p 5000:5000 tugas

      - name: Build Docker image
        run: docker build -t yohaniyuviena/flask-hello-world .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push yohaniyuviena/flask-hello-world
